NSE_TICKERS = [
    "ADANIENT.NS", "ADANIPORTS.NS", "APOLLOHOSP.NS", "ASIANPAINT.NS", "AXISBANK.NS",
    "BAJAJ-AUTO.NS", "BAJFINANCE.NS", "BAJAJFINSV.NS", "BEL.NS", "BHARTIARTL.NS", "BPCL.NS", "BRITANNIA.NS",
    "CIPLA.NS", "COALINDIA.NS", 
    "DRREDDY.NS",
    "EICHERMOT.NS", "ETERNAL.NS", 
    "GRASIM.NS", 
    "HCLTECH.NS", "HDFCBANK.NS", "HDFCLIFE.NS", "HEROMOTOCO.NS", "HINDALCO.NS", "HINDUNILVR.NS",
    "ICICIBANK.NS", "INDIGO.NS", "INDUSINDBK.NS", "INFY.NS", "ITC.NS", 
    "JIOFIN.NS", "JSWSTEEL.NS", 
    "KOTAKBANK.NS", 
    "LT.NS", 
    "M&M.NS", "MARUTI.NS", "MAXHEALTH.NS",
    "NESTLEIND.NS", "NTPC.NS", 
    "ONGC.NS", 
    "POWERGRID.NS",
    "RELIANCE.NS", 
    "SBILIFE.NS", "SBIN.NS", "SHRIRAMFIN.NS", "SUNPHARMA.NS",
    "TATACONSUM.NS", "TMPV.NS", "TATASTEEL.NS", "TCS.NS", "TECHM.NS", "TITAN.NS", "TRENT.NS", 
    "ULTRACEMCO.NS", 
    "WIPRO.NS"
]
alphas = [
    "Sub(Add(close, 0.5), 0.5)",
    "Mul(Sub(0, 1), Corr(Delta(xLog(volume), 2), Div(Sub(close, open), open), 6))",
    "Mul(Sub(0, 1), Corr(open, volume, 10))",
    "Mul(Sub(0, 1), low)",
    "Mul(Sub(open, Mean(close, 10)), Mul(Sub(0, 1), xAbs(Sub(close, close))))",
    "Mul(Sub(0, 1), Corr(open, volume, 10))",
    "Sub(0, Delta(close, 7))",
    "Mul(Sub(0, 1), Sub(Mul(Sum(open, 5), Sum(Div(Delta(close, 1), Ref(close, 1)), 5)), Ref(Mul(Sum(open, 5), Sum(Div(Delta(close, 1), Ref(close, 1)), 5)), 10)))",
    "Delta(close, 1)",
    "Delta(close, 1)",
    "Mul(Add(Max(Sub(close, close), 3), Min(Sub(close, close), 3)), Delta(volume, 3))",
    "Mul(Delta(volume, 1), Mul(Sub(0, 1), Delta(close, 1)))",
    "Mul(Sub(0, 1), Cov(close, volume, 5))",
    "Mul(Mul(Sub(0, 1), Delta(Div(Delta(close, 1), Ref(close, 1)), 3)), Corr(open, volume, 10))",
    "Mul(Sub(0, 1), Sum(Corr(high, volume, 3), 3))",
    "Mul(Sub(0, 1), Cov(high, volume, 5))",
    "Mul(Mul(Sub(0, 1), close), Mul(Delta(Delta(close, 1), 1), Div(volume, Mean(volume, 20))))",
    "Mul(Sub(0, 1), Add(Add(Std(xAbs(Sub(close, open)), 5), Sub(close, open)), Corr(close, open, 10)))",
    "Mul(Mul(Sub(0, 1), Add(Sub(close, Ref(close, 7)), Delta(close, 7))), Add(1, Sum(Div(Delta(close, 1), Ref(close, 1)), 50)))",
    "Mul(Mul(Sub(0, 1), Sub(open, Ref(high, 1))), Mul(Sub(open, Ref(close, 1)), Sub(open, Ref(low, 1))))",
    "Div(Add(Mean(close, 8), Std(close, 8)), Mean(close, 2))",
    "Mul(Sub(0, 1), Mul(Delta(Corr(high, volume, 5), 5), Std(close, 20)))",
    "Sub(0, Delta(high, 2))",
    "Mul(Sub(0, 1), Sub(close, Min(close, 50)))",
    "Mul(Mul(Mul(Sub(0, 1), Div(Delta(close, 1), Ref(close, 1))), volume), Sub(high, close))",
    "Mul(Sub(0, 1), Max(Corr(volume, high, 5), 3))",
    "Sub(0, Corr(volume, close, 6))",
    "Sub(Add(Corr(volume, low, 5), Div(Add(high, low), 2)), close)",
    "Add(Min(xLog(Sum(Min(close, 2), 1)), 5), Sub(0, Div(Delta(close, 1), Ref(close, 1))))",
    "Div(Mul(Sub(1, close), Sum(volume, 5)), Sum(volume, 20))",
    "Add(WMA(Sub(0, Delta(close, 10)), 10), Sub(0, Delta(close, 3)))",
    "Add(Sub(Mean(close, 7), close), Mul(20, Corr(close, Ref(close, 5), 50)))",
    "Sub(0, Sub(1, Div(open, close)))",
    "Add(Sub(1, Div(Std(Div(Delta(close, 1), Ref(close, 1)), 2), Std(Div(Delta(close, 1), Ref(close, 1)), 5))), Sub(1, Delta(close, 1)))",
    "Mul(Mul(volume, Sub(1, Add(Sub(close, high), low))), Sub(1, Div(Delta(close, 1), Ref(close, 1))))",
    "Add(Add(Corr(Sub(close, open), Ref(volume, 1), 15), Sub(open, close)), Sub(Mean(close, 50), open))",
    "Add(Corr(Ref(Sub(open, close), 1), close, 50), Sub(open, close))",
    "Mul(Mul(Sub(0, 1), close), Div(close, open))",
    "Mul(Mul(Sub(0, 1), Mul(Delta(close, 7), Sub(1, WMA(volume, 9)))), Add(1, Sum(Div(Delta(close, 1), Ref(close, 1)), 50)))",
    "Mul(Mul(Sub(0, 1), Std(high, 10)), Corr(high, volume, 10))",
    "Sub(Div(Add(high, low), 2), close)",
    "Div(Sub(close, close), Add(close, close))",
    "Mul(Div(volume, Mean(volume, 20)), Sub(0, Delta(close, 7)))",
    "Mul(Sub(0, 1), Corr(high, volume, 5))",
    "Mul(Sub(0, 1), Mul(Mul(Mean(Ref(close, 5), 20), Corr(close, volume, 2)), Corr(Sum(close, 5), Sum(close, 20), 2)))",
    "Sub(0, Sub(close, Ref(close, 1)))",
    "Sub(Div(Mul(Div(1, close), volume), Mean(volume, 20)), Delta(close, 5))",
    "Div(Mul(Corr(Delta(close, 1), Delta(Ref(close, 1), 1), 50), Delta(close, 1)), close)",
    "Sub(0, Sub(close, Ref(close, 1)))",
    "Mul(Sub(0, 1), Max(Corr(volume, close, 5), 5))",
    "Sub(0, Sub(close, Ref(close, 1)))",
    "Mul(Mul(Add(Sub(0, Min(low, 5)), Ref(Min(low, 5), 5)), Mean(Div(Delta(close, 1), Ref(close, 1)), 20)), volume)",
    "Mul(Sub(0, 1), Delta(Div(Sub(Sub(close, low), Sub(high, close)), Sub(close, low)), 9))",
    "Div(Mul(Sub(0, 1), Mul(Sub(low, close), open)), Mul(Sub(low, high), close))",
    "Mul(Sub(0, 1), Corr(Div(Sub(close, Min(low, 12)), Sub(Max(high, 12), Min(low, 12))), volume, 6))",
    "Sub(0, Mul(Mean(Div(Delta(close, 1), Ref(close, 1)), 10), Div(Delta(close, 1), Ref(close, 1))))",
    "Sub(0, Div(Sub(close, close), WMA(close, 2)))",
    "Mul(Sub(0, 1), WMA(Corr(close, volume, 4), 8))",
    "Mul(Sub(0, 1), WMA(Corr(close, volume, 4), 16))",
    "Sub(0, Sub(Mul(2, Div(Sub(Sub(close, low), Sub(high, close)), Sub(high, low))), close))",
    "Less(Sub(close, Min(close, 16)), Corr(close, volume, 18))",
    "Mul(Sub(0, 1), Less(Corr(close, volume, 10), open))",
    "Mul(Sub(0, 1), Sub(WMA(Delta(close, 2), 8), WMA(Corr(open, volume, 14), 12)))",
    "Mul(Sub(0, 1), Less(Corr(open, volume, 17), Delta(Add(high, low), 4)))",
    "Mul(Sub(0, 1), Less(Corr(open, volume, 6), Sub(open, Min(open, 14))))",
    "Mul(Sub(0, 1), Add(WMA(Delta(close, 4), 7), WMA(Div(Sub(low, close), Sub(open, Div(Add(high, low), 2))), 11)))",
    "Mul(Sub(0, 1), Sub(high, Min(high, 2)))",
    "Mul(Sub(0, 1), Less(Corr(high, volume, 9), Delta(close, 1)))",
    "Mul(Sub(0, 1), Max(Delta(close, 3), 5))",
    "Mul(Sub(0, 1), Delta(close, 1))",
    "Max(WMA(Corr(close, volume, 18), 4), WMA(Sub(low, close), 16))",
    "Div(WMA(Corr(Div(Add(high, low), 2), volume, 9), 10), WMA(Corr(close, volume, 7), 3))",
    "Mul(Sub(0, 1), Max(WMA(Delta(close, 5), 3), WMA(Div(Delta(open, 2), open), 3)))",
    "Mul(Sub(0, 1), Less(Corr(close, volume, 15), Corr(high, volume, 11)))",
    "Less(Corr(close, volume, 4), Corr(low, volume, 12))",
    "Mul(Sub(0, 1), Max(WMA(Delta(close, 1), 12), WMA(Corr(low, volume, 8), 17)))",
    "Min(WMA(Sub(Add(low, high), Add(close, high)), 20), WMA(Corr(low, volume, 3), 6))",
    "Mul(Corr(low, volume, 20), Corr(close, volume, 6))",
    "Less(Delta(close, 1), Corr(close, volume, 15))",
    "Mul(Sub(0, 1), Delta(open, 4))",
    "Mul(Sub(0, 1), Less(xLog(Corr(close, volume, 8)), Corr(close, volume, 5)))",
    "Mul(Sub(0, 1), Min(WMA(Delta(open, 1), 15), WMA(Corr(volume, open, 17), 7)))",
    "Div(Mul(Ref(Div(Sub(high, low), Mean(close, 5)), 2), volume), Div(Div(Sub(high, low), Mean(close, 5)), Sub(close, close)))",
    "Sub(close, Max(close, 15))",
    "Corr(high, volume, 10)",
    "Mul(Sub(0, 1), Less(Corr(close, volume, 6), Sub(Add(open, close), Add(close, open))))",
    "Mul(Sub(0, 1), Max(WMA(Delta(close, 2), 3), WMA(xAbs(Corr(volume, close, 13)), 5)))",
    "Min(WMA(Sub(Add(open, low), Add(high, close)), 8), WMA(Corr(close, volume, 8), 7))",
    "Sub(WMA(Corr(low, volume, 7), 6), WMA(Delta(close, 3), 10))",
    "Mul(Sub(0, 1), Sub(close, Max(close, 5)))",
    "Mul(Sub(0, 1), Sub(WMA(Corr(close, volume, 10), 16), WMA(Corr(close, volume, 4), 3)))",
    "Min(WMA(Less(Add(Div(Add(high, low), 2), close), Add(low, open)), 15), WMA(Corr(low, volume, 8), 7))",
    "Div(WMA(Corr(close, volume, 17), 20), WMA(Delta(close, 3), 16))",
    "Mul(Sub(0, 1), Sub(close, Min(close, 12)))",
    "Less(Sub(open, Min(open, 12)), Corr(Add(high, low), volume, 13))",
    "Mul(Sub(0, 1), Max(WMA(Corr(close, volume, 4), 4), WMA(Corr(close, volume, 4), 14)))",
    "Mul(Sub(0, 1), Sub(WMA(Delta(low, 3), 20), WMA(Corr(low, volume, 5), 16)))",
    "Sub(WMA(Corr(close, volume, 5), 7), WMA(Corr(open, volume, 20), 8))",
    "Mul(Sub(0, 1), Less(Corr(Add(high, low), volume, 9), Corr(low, volume, 6)))",
    "Mul(Sub(0, 1), Mul(Sub(Div(Sub(Sub(close, low), Sub(high, close)), Sub(high, low)), Corr(close, volume, 5)), Div(volume, Mean(volume, 20))))",
    "Div(Sub(close, open), Add(Sub(high, low), 0.001))"
]